### What's going wrong?

In [54]:
import numpy as np
from scipy.stats import norm

In [55]:
k = 2
data = np.random.uniform(low=0, high=10, size=(10,1))

In [56]:
params = list(zip(
    list(np.random.uniform(low=np.min(data), high=np.max(data), size=k)), 
    list(np.random.uniform(low=np.std(data, ddof=1)/2, high=np.std(data, ddof=1)*2, size=k))
))

In [57]:
weights = np.random.uniform(size=k)
weights /= np.sum(weights)

In [79]:
probs = []
for mean, std in params:
    probs.append(norm.pdf(data, loc=mean, scale=std))

probs = np.hstack(probs) * weights
probs /= np.sum(probs, axis=1, keepdims=True)
probs

array([[0.17677919, 0.82322081],
       [0.14745926, 0.85254074],
       [0.14786333, 0.85213667],
       [0.36666473, 0.63333527],
       [0.13615487, 0.86384513],
       [0.13611197, 0.86388803],
       [0.1359648 , 0.8640352 ],
       [0.1411489 , 0.8588511 ],
       [0.19234393, 0.80765607],
       [0.14838542, 0.85161458]])

In [80]:
n = np.sum(probs, axis=0) 
weights = n / data.shape[0]
n

array([1.72887639, 8.27112361])

In [81]:
weights

array([0.17288764, 0.82711236])

In [82]:
means = np.sum(probs * data, axis=0) / n
stdevs = np.sum(probs * ((np.repeat(data, means.shape[0], axis=1) - means) ** 2), axis=0) / n
params = list(zip(
        list(means),
        list(stdevs)
))
params

[(5.307243894200343, 6.512668247082408),
 (4.468485174031444, 4.327114763193506)]